name: Build check

on:
    push:
        branches-ignore:
            -   main

jobs:
    build-check:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Install dependencies
                uses: php-actions/composer@v6

            -   name: Check for uncommitted files
                run: ./.github/workflows/build-check.sh
