name: Unit tests

on:
    push:
        branches-ignore:
            -   main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup composer
                uses: php-actions/composer@v6

            -   name: Run PHPUnit Tests
                uses: php-actions/phpunit@v3
                with:
                    args: --colors=always --testdox tests
                    bootstrap: vendor/autoload.php
                    php_version: "8.2"
